# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os
import glob

# Set Data Path

In [2]:
data_path = "../Data/"

# View All Files

In [3]:
all_files = glob.glob(os.path.join(data_path, "*", "*.csv"))
print("Total CSV Files:", len(all_files))

Total CSV Files: 344

# Read and Merge All CSV Files

In [4]:
df_list = []
for file in all_files:
    # Read CSV file
    temp_df = pd.read_csv(file)
    # Extract filename
    filename = os.path.basename(file)
    
    # Example filename:
    # delhi_01_04_2022.csv
    
    date_part = filename.replace("delhi_", "").replace(".csv", "")
    
    # Convert to datetime
    date = pd.to_datetime(date_part, format="%d_%m_%Y")
    
    # Add new Date column
    temp_df['Date'] = date
    
    # Append dataframe
    df_list.append(temp_df)

# Merge all dataframes
df = pd.concat(df_list, ignore_index=True)

print("All files merged successfully!")

All files merged successfully!

In [5]:
df.head()

  TIMESLOT    DELHI     BRPL    BYPL     NDPL    NDMC    MES       Date
0    00:00   4256.1  1762.03  970.96  1311.58  149.46  21.53 2022-04-06
1    00:05  4190.06   1730.4  959.13   1290.7  146.01  21.36 2022-04-06
2    00:10  4181.79  1726.67   961.5  1286.69  146.07  21.34 2022-04-06
3    00:15  4176.84  1714.84  964.93  1289.69  146.49   21.2 2022-04-06
4    00:20  4127.07  1700.86  950.89  1268.66  145.86  21.21 2022-04-06

In [6]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 92268 entries, 0 to 92267
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   TIMESLOT  92268 non-null  object
 1   DELHI     92268 non-null  object
 2   BRPL      92268 non-null  object
 3   BYPL      92268 non-null  object
 4   NDPL      92268 non-null  object
 5   NDMC      92268 non-null  object
 6   MES       92268 non-null  object
 7   Date      92268 non-null  datetime64[us]
dtypes: datetime64[us](1), object(7)
memory usage: 5.6+ MB

In [7]:
# Check shape
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 92268
Columns : 8

In [8]:
# Check for missing values
df.isnull().sum()

TIMESLOT    0
DELHI       0
BRPL        0
BYPL        0
NDPL        0
NDMC        0
MES         0
Date        0
dtype: int64

In [9]:
# Remove duplicates
duplicate_rows = df.duplicated().sum()
print("Duplicate Rows:", duplicate_rows)
df = df.drop_duplicates()
print("Duplicates Removed!")

Duplicate Rows: 0
Duplicates Removed!

# Create Time Features

In [10]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Day_Name'] = df['Date'].dt.day_name()

In [11]:
df['Total_Consumption'] = (
    df['BRPL'] +
    df['BYPL'] +
    df['NDPL'] +
    df['NDMC'] +
    df['MES']
)

print("Total_Consumption column created successfully!")

Total_Consumption column created successfully!

In [12]:
# Convert TIMESLOT to String
df['TIMESLOT'] = df['TIMESLOT'].astype(str)

# Check Statistical Summary

In [13]:
df.describe()

                             Date     Year         Month           Day
count                       92268  92268.0  92268.000000  92268.000000
mean   2022-06-22 22:42:17.651189   2022.0      6.237764     15.459292
min           2022-01-01 00:00:00   2022.0      1.000000      1.000000
25%           2022-03-30 00:00:00   2022.0      3.000000      8.000000
50%           2022-06-22 00:00:00   2022.0      6.000000     15.000000
75%           2022-09-17 00:00:00   2022.0      9.000000     23.000000
max           2022-12-10 00:00:00   2022.0     12.000000     31.000000
std                           NaN      0.0      3.240786      8.788762

In [14]:
# final dateset shape
print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (92268, 13)

# Save Cleaned Dataset

In [15]:
output_path = "../Output/cleaned_data.csv"
df.to_csv(output_path, index=False)
print("Cleaned data saved successfully!")

Cleaned data saved successfully!